language: go
go:
  - 1.5
  - 1.6

addons:
  apt:
    packages:
      libpam0g-dev
      pamtester

sudo: required
dist: trusty

install:
  - go get -v -t ./...
script:
  - go test -v ./store
  - go test -v ./sasl

branches:
  only:
    - master
